{
 "title": "Teku",
 "description": "Dashboard to monitor multiple Teku services on the same beacon chain",
 "tags": [
  "eth2.0",
  "ethereum",
  "teku"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "system", "label": "System", "query": "beacon_slot" }
  ]
 },
 "panels": [
  {
   "title": "VALIDATOR",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1", "legendFormat": "VALIDATOR" }
   ]
  },
  {
   "title": "Local Validators",
   "type": "stat",
   "description": "Number of local validators",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(validator_local_validator_count{instance=\"validator.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Published Blocks",
   "type": "stat",
   "description": "Number of blocks published",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_published_block_total{instance=\"validator.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Published Attestations",
   "type": "stat",
   "description": "Number of attestations published",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_published_attestation_total{instance=\"validator.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Published Aggregates",
   "type": "stat",
   "description": "Number of aggregates published",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(validator_beacon_node_published_aggregate_total{instance=\"validator.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Total Validators",
   "type": "stat",
   "description": "Total number of active validators in the network.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_current_active_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Attestation Performance",
   "type": "graph",
   "description": "Percentage of attestations in each epoch with the correct head root, correct target root and that were successfully included in blocks.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "validator_performance_included_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_expected_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Included"
    },
    {
     "expr": "validator_performance_correct_head_block_count{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_included_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Correct Head"
    },
    {
     "expr": "validator_performance_correct_target_count{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_included_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Correct Target"
    },
    {
     "expr": "\n(\nvalidator_performance_correct_head_block_count{instance=\"validator.teku-gnosis.dappnode:8008\"} - (validator_performance_expected_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} - validator_performance_correct_head_block_count{instance=\"validator.teku-gnosis.dappnode:8008\"}) +\nvalidator_performance_correct_target_count{instance=\"validator.teku-gnosis.dappnode:8008\"} - (validator_performance_expected_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} - validator_performance_correct_target_count{instance=\"validator.teku-gnosis.dappnode:8008\"}) +\nvalidator_performance_included_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} - (validator_performance_expected_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} - validator_performance_included_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"}) +\n(0.875  * validator_performance_included_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_inclusion_distance_average{instance=\"validator.teku-gnosis.dappnode:8008\"})\n) / validator_performance_expected_attestations{instance=\"validator.teku-gnosis.dappnode:8008\"} / 3.875",
     "legendFormat": "{{service}} Attestation Rewards Earned"
    },
    {
     "expr": "validator_performance_included_sync_committee_messages{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_expected_sync_committee_messages{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Included Signatures"
    },
    {
     "expr": "validator_performance_produced_sync_committee_messages{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_expected_sync_committee_messages{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Produced Signatures"
    },
    {
     "expr": "validator_performance_correct_sync_committee_messages{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_produced_sync_committee_messages{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Correct Signatures"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Distance (slots)",
   "type": "graph",
   "description": "Number of slots between when an attestation is created to when it is included in a block. The minimum possible inclusion distance is 1.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "validator_performance_inclusion_distance_min{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Minimum"
    },
    {
     "expr": "validator_performance_inclusion_distance_average{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Average"
    },
    {
     "expr": "validator_performance_inclusion_distance_max{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Maximum"
    }
   ]
  },
  {
   "title": "Included Blocks",
   "type": "graph",
   "description": "Percentage of blocks produced in each epoch that were successfully included in the canonical chain.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "validator_performance_included_blocks{instance=\"validator.teku-gnosis.dappnode:8008\"} / validator_performance_expected_blocks{instance=\"validator.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Included Blocks"
    }
   ]
  },
  {
   "title": "BEACON CHAIN",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "Current slot",
   "type": "stat",
   "description": "Current slot according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_slot{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Head slot",
   "type": "stat",
   "description": "Slot of the latest imported block",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_head_slot{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Justified Epoch",
   "type": "stat",
   "description": "Current justified epoch",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_current_justified_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Finalized Epoch",
   "type": "stat",
   "description": "Current finalized epoch",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_finalized_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Peer Count",
   "type": "stat",
   "description": "Total number of peers connected to the selected nodes.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(beacon_peer_count{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "The current epoch according to system time",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Slots Behind",
   "type": "stat",
   "description": "Number of slots the head block is behind.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(beacon_slot{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - beacon_head_slot{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Justification Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that justification has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(min(beacon_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - beacon_current_justified_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - 1), 0)"
    }
   ]
  },
  {
   "title": "Finalisation Delay (epochs)",
   "type": "stat",
   "description": "Number of epochs that finalisation has been delayed.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp_min(min(beacon_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - beacon_finalized_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - 2), 0)"
    }
   ]
  },
  {
   "title": "Correct Attestation Rate",
   "type": "stat",
   "description": "Percentage of validators which voted for the correct target in the previous epoch.",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(beacon_previous_correct_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} / beacon_previous_active_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})"
    }
   ]
  },
  {
   "title": "Trailing Distance",
   "type": "graph",
   "description": "Number of slots the head block is behind the current slot. Empty slots may mean the head block trails by a few slots.",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "beacon_slot{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - beacon_head_slot{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} Head Slot"
    },
    {
     "expr": "clamp_min(min(beacon_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - beacon_current_justified_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - 1) without (service), 0)",
     "legendFormat": "Justification Delay"
    },
    {
     "expr": "clamp_min(min(beacon_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - beacon_finalized_epoch{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} - 2) without (service), 0)",
     "legendFormat": "Finalisation Delay"
    }
   ]
  },
  {
   "title": "Participation Rate",
   "type": "graph",
   "description": "Overall participation rate in the chain. The Correct Validators must be above 2/3rd for the chain to finalize.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "max(beacon_previous_live_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} / beacon_previous_active_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})",
     "legendFormat": "Live Validators"
    },
    {
     "expr": "max(beacon_previous_correct_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} / beacon_previous_active_validators{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})",
     "legendFormat": "Correct Validators"
    },
    {
     "expr": "max(beacon_previous_live_sync_committee{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"} / (512 * 32))",
     "legendFormat": "Sync Committee Participation"
    }
   ]
  },
  {
   "title": "Gossip Messages",
   "type": "graph",
   "description": "Rate of gossip messages received per second.",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(libp2p_gossip_messages_total{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}[1m])",
     "legendFormat": "{{service}} {{topic}}"
    }
   ]
  },
  {
   "title": "SYSTEM",
   "type": "singlestat",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "1" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}[1m])",
     "legendFormat": "{{service}} {{job}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} {{job}} {{pool}} Used"
    },
    {
     "expr": "sum by (service) (jvm_memory_pool_bytes_used{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})",
     "legendFormat": "{{service}} {{job}} {{pool}} Used Total"
    },
    {
     "expr": "process_resident_memory_bytes{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} {{job}} {{pool}} Process Total"
    },
    {
     "expr": " (jvm_memory_pool_bytes_max{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"})",
     "legendFormat": "{{service}} {{job}} {{pool}} Max"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}",
     "legendFormat": "{{service}} System Memory"
    }
   ]
  },
  {
   "title": "GC Time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"beacon-chain.teku-gnosis.dappnode:8008\"}[1m])",
     "legendFormat": "{{service}} {{gc}}"
    }
   ]
  }
 ]
}